# Generated by Django 3.1.5 on 2021-01-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('pass_word', models.CharField(max_length=10, verbose_name='密码')),
                ('info', models.TextField(max_length=100, verbose_name='个人说明')),
            ],
        ),
    ]
