# Generated by Django 3.1.5 on 2021-01-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pass_word',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
    ]
